name: takotori-web
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug